spring:
  application:
    name: security-management
  data:
    mongodb:
      uri: mongodb://mazkte:t3st@localhost:27017/?authMechanism=SCRAM-SHA-256
      database: security-mgnt
  cloud:
    vault:
      enabled: true
      uri: http://localhost:8200
      token: MASTER-VAULT
      kv:
        backend: secret
        default-context: security-mgnt

jwt:
  secret: "CKqHITrMPzepvWmczHw+O4QpWgYKlX0b3hqrBxYWu2UWN9Xrr2zKq8ziOqMOfYiLSP5pJYR2FOoJpRGLUrGVeQ=="
  expiration: 60

server:
  port: 8081
